language: objective-c
osx_image: xcode8
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_FRAMEWORK_SCHEME="Bukoli"
  - WORKSPACE=Example/Bukoli.xcworkspace
  - IOS_SDK=iphonesimulator10.0
  - EXAMPLE_SCHEME="Bukoli-Example"

  matrix:
      - DESTINATION="OS=10.0,name=iPhone 7 Plus" SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK" RUN_TESTS="NO" BUILD_EXAMPLE="YES" POD_LINT="YES"
      - DESTINATION="OS=9.0,name=iPhone 6"       SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK" RUN_TESTS="NO" BUILD_EXAMPLE="YES" POD_LINT="NO"
      - DESTINATION="OS=8.0,name=iPhone 4S"      SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK" RUN_TESTS="NO" BUILD_EXAMPLE="YES" POD_LINT="NO"
  before_install:
    - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  script:
    - set -o pipefail
    - xcodebuild -version
    - xcodebuild -showsdks

    # Build Example in Debug if specified
    - if [ $BUILD_EXAMPLE == "YES" ]; then
        xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
      fi

    # Run `pod lib lint` if specified
    - if [ $POD_LINT == "YES" ]; then
        pod lib lint;
      fi
